name: Frontend Tests
on:
  workflow_run:
    workflows: ["CI/CD"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: Run npm install
        working-directory: ./front
        run: npm install

      - name: Run npm test
        working-directory: ./front
        run: npm run test:prod

      - name: Upload coverage report
        working-directory: ./front
        uses: actions/upload-artifact@v3
        with:
          name: karma-report
          path: front/coverage
